#Config thông tin của nhiều role(production, develop) truy cập trên cùng 1 file 
spring:
   application:
      name: demoservice
wellcome : Wellcom my app demo
#debug : true

#Khai bao ten va duong dan file log
logging.file.path : /var/tmp/
logging.file.name : /var/tmp/mylog.log

server:
   port: 8080

---
spring:
   profiles: dev
   application:
      name: demoservice
server:
   port: 9090

---
spring: 
   profiles: prod
   application:
      name: demoservice
server: 
   port: 4431